Metrics/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*_test.rb'
    - 'spec/**/*_spec.rb'
    - 'spec/**/*_context.rb'
  ExcludedMethods:
    - resource
    - params
    - requires
    - route_param

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect
    - uniq